Added zondax repo files that was missing
Without that, on make install you get that error

mkdir -p /root/genesisd/build/
go build -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=evmos -X github.com/cosmos/cosmos-sdk/version.AppName=genesisd -X github.com/cosmos/cosmos-sdk/version.Version=0.3.0 -X github.com/cosmos/cosmos-sdk/version.Commit=23d20d043bc08dc2cb7445583756d705e2a70c49 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.24 -w -s' -trimpath -o /root/genesisd/build/ ./...
# github.com/zondax/hid
vendor/github.com/zondax/hid/hid_enabled.go:23:11: fatal error: os/threads_posix.c: No such file or directory
   23 |  #include "os/threads_posix.c"
      |           ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

These files solves the missing files in dependency